name: Update Tracking Issue

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual testing via GitHub UI

permissions:
  issues: write

concurrency: # Ensure we never have more than one instance of this action running
  group: update-tracking-issue-global
  cancel-in-progress: true

jobs:
  update-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Deps
        run: npm i

      - name: Determine Issue Title
        id: issue-title
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "title=PR #${{ github.event.pull_request.number }} issue preview" >> $GITHUB_ENV
          else
            echo "title=@main Tracking: Open Issues with \`tracking\` label" >> $GITHUB_ENV
          fi

      - name: Run Label Tracker Action
        uses: ./ # use the action.yml in repo root
        with:
          label: 'tracking'
          issue_title: ${{ env.title }}
